import { useEffect, useState } from "react";
import StockSearch from "../components/StockSearch";
import { getAdvancedAnalytics, getAnalysisHistory, getDailyBriefing, getOpportunities, getPortfolioIntelligence, getReconciliation, getStockIntelligence, getTradingView, getTradingGeneral, type AdvancedAnalytics, type DailyBriefing, type HistoryItem, type IntelligenceResponse, type OpportunityResponse, type ReconciliationResponse, type TradingViewResponse, type TradingGeneral } from "../services/intelligence";
import { getAlerts, markAlertRead, markAllAlertsRead, type AlertItem } from "../services/alerts";

export function IntelligencePanel() {
  const [analytics,setAnalytics]=useState<AdvancedAnalytics|null>(null),[reconciliation,setReconciliation]=useState<ReconciliationResponse|null>(null),[portfolio,setPortfolio]=useState<IntelligenceResponse|null>(null),[opportunities,setOpportunities]=useState<OpportunityResponse|null>(null),[tradingView,setTradingView]=useState<TradingViewResponse|null>(null),[stock,setStock]=useState<IntelligenceResponse|null>(null),[briefing,setBriefing]=useState<DailyBriefing|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[alerts,setAlerts]=useState<AlertItem[]>([]),[trading,setTrading]=useState<TradingGeneral|null>(null),[symbol,setSymbol]=useState(""),[error,setError]=useState("");
  useEffect(()=>{void Promise.allSettled([getAdvancedAnalytics(),getReconciliation(),getPortfolioIntelligence(),getOpportunities(),getTradingView(),getDailyBriefing(),getAnalysisHistory(),getAlerts(),getTradingGeneral()]).then(r=>{const [a,b,c,d,e,f,g,h,i]=r;if(a.status==="fulfilled")setAnalytics(a.value);if(b.status==="fulfilled")setReconciliation(b.value);if(c.status==="fulfilled")setPortfolio(c.value);if(d.status==="fulfilled")setOpportunities(d.value);if(e.status==="fulfilled")setTradingView(e.value);if(f.status==="fulfilled")setBriefing(f.value);if(g.status==="fulfilled")setHistory(g.value);if(h.status==="fulfilled")setAlerts(h.value);if(i.status==="fulfilled")setTrading(i.value);if(r.some(x=>x.status==="rejected"))setError("Some intelligence data is unavailable. Other dashboard sections remain available.");});},[]);
  async function analyseStock(requested=symbol.trim().toUpperCase()){if(!requested)return;try{setError("");setSymbol(requested);setStock(await getStockIntelligence(requested));}catch{setError("Stock analysis is unavailable. Check the symbol and try again.");}}
  async function readAllAlerts(){await markAllAlertsRead();setAlerts(x=>x.map(i=>({...i,is_read:true})));} async function readAlert(id:number){await markAlertRead(id);setAlerts(x=>x.map(i=>i.id===id?{...i,is_read:true}:i));}
  return <section className="mt-8 grid gap-4 lg:grid-cols-2">
    <div className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Trading General</h2><p className="mt-1 text-xs text-slate-500">A retrospective scorecard of your recorded BUY/SELL behavior. It does not predict returns.</p>{trading?<div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-sm text-slate-500">Realized P/L</p><p className={`text-2xl font-bold ${trading.realized_pnl>=0?"text-emerald-700":"text-red-700"}`}>₹{trading.realized_pnl.toFixed(2)}</p></div><div><p className="text-sm text-slate-500">Win rate</p><p className="text-2xl font-bold">{trading.win_rate_percent.toFixed(1)}%</p></div><div><p className="text-sm text-slate-500">Profit factor</p><p className="text-2xl font-bold">{trading.profit_factor==null?"—":trading.profit_factor.toFixed(2)}</p></div><div><p className="text-sm text-slate-500">Avg win / loss</p><p className="font-semibold text-emerald-700">₹{trading.average_win.toFixed(2)}</p><p className="font-semibold text-red-700">₹{trading.average_loss.toFixed(2)}</p></div><div><p className="text-sm text-slate-500">Expectancy / closed lot</p><p className="text-xl font-bold">₹{trading.expectancy_per_trade.toFixed(2)}</p></div><div><p className="text-sm text-slate-500">Strategy score</p><p className="text-xl font-bold">{trading.strategy_score}/100 · {trading.strategy_label}</p></div></div>:<p className="mt-3 text-sm text-slate-500">Add closed trades to generate your trading scorecard.</p>}{trading&&<div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-lg bg-emerald-50 p-3"><b>What is working</b>{trading.profit_patterns.length?<ul className="mt-1 list-disc pl-5 text-sm">{trading.profit_patterns.map(x=><li key={x}>{x}</li>)}</ul>:<p className="text-sm">No strong pattern yet.</p>}</div><div className="rounded-lg bg-red-50 p-3"><b>Loss patterns</b>{trading.loss_patterns.length?<ul className="mt-1 list-disc pl-5 text-sm">{trading.loss_patterns.map(x=><li key={x}>{x}</li>)}</ul>:<p className="text-sm">No recurring loss pattern detected.</p>}</div><div className="rounded-lg bg-slate-50 p-3"><b>Rules to test</b><ul className="mt-1 list-disc pl-5 text-sm">{trading.suggested_rules.map(x=><li key={x}>{x}</li>)}</ul></div></div>}{trading&&<p className="mt-3 text-xs text-slate-500">{trading.disclaimer}</p>}</div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Portfolio risk</h2>{analytics?<p className="mt-3 text-sm">{analytics.risk_summary} · Concentration {analytics.concentration_percent.toFixed(1)}% · Diversification {analytics.diversification_score.toFixed(1)}</p>:<p className="mt-3 text-sm text-slate-500">Risk analytics are unavailable.</p>}</div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Reconciliation</h2>{reconciliation?<p className="mt-3 text-sm">{reconciliation.summary.matched} matched, {reconciliation.summary.quantity_mismatches} quantity differences.</p>:<p className="mt-3 text-sm text-slate-500">No broker reconciliation available.</p>}</div>
    <div className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-semibold">AI Portfolio Analysis</h2><p className="mt-1 text-xs text-slate-500">AI-generated analysis — informational only. It never executes trades or guarantees outcomes.</p>{portfolio?<div className="mt-3 text-sm"><p><strong>{portfolio.analysis.signal}</strong> · Confidence {portfolio.analysis.confidence}%</p><p className="mt-2">{portfolio.analysis.summary}</p><p className="mt-2"><strong>Risks:</strong> {portfolio.analysis.risks.join(" ")||"No specific risks identified."}</p><p className="mt-2"><strong>Opportunities:</strong> {portfolio.analysis.opportunities.join(" ")||"No specific opportunities identified."}</p></div>:<p className="mt-3 text-sm text-slate-500">Preparing advisory portfolio analysis…</p>}</div>
    <div className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-semibold">AI Daily Briefing</h2>{briefing?<div className="mt-3 text-sm"><p>{briefing.headline}</p><p className="mt-2">{briefing.portfolio_summary}</p><p className="mt-2"><strong>Risk:</strong> {briefing.risk_summary}</p><p className="mt-2"><strong>Watch:</strong> {briefing.watch_items.join(", ")||"No priority watch items."}</p></div>:<p className="mt-3 text-sm text-slate-500">Daily briefing is unavailable.</p>}</div>
    <div className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-semibold">Stock Analysis</h2><div className="mt-3 flex flex-col gap-2 sm:flex-row"><div className="min-w-0 flex-1"><StockSearch value={symbol} onChange={setSymbol} onSelect={i=>void analyseStock(i.symbol)} placeholder="Search Indian stock..."/></div><button className="rounded bg-slate-900 px-4 py-2 text-white" onClick={()=>void analyseStock()} type="button">Analyze Stock</button></div>{stock&&<div className="mt-4 text-sm"><strong>{String(stock.context_summary.symbol)}: {stock.analysis.signal}</strong> · {stock.analysis.confidence}%<p className="mt-1">{stock.analysis.summary}</p><p className="mt-1"><strong>Why:</strong> {stock.analysis.reasons.join(" ")}</p></div>}</div>
    <div className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-semibold">Opportunity Scanner</h2>{opportunities?.opportunities.length?<div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Symbol</th><th>Score</th><th>Signal</th><th>Reason</th><th>Risk</th></tr></thead><tbody>{opportunities.opportunities.map(i=><tr className="border-t" key={i.symbol}><td className="py-2"><button className="font-semibold underline" onClick={()=>void analyseStock(i.symbol)} type="button">{i.symbol}</button></td><td>{i.score}</td><td>{i.signal}</td><td>{i.reasons[0]}</td><td>{i.risks[0]??"—"}</td></tr>)}</tbody></table></div>:<p className="mt-3 text-sm text-slate-500">No symbols with sufficient technical data are available to scan.</p>}</div>
    <div className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-semibold">Short-Term Trading View</h2>{tradingView?<div className="mt-3 text-sm"><p>Potential setups: {tradingView.market_candidates.length} · BUY {tradingView.buy_candidates.length} · HOLD {tradingView.hold_candidates.length} · SELL {tradingView.sell_candidates.length}</p><p className="mt-2">Strongest momentum: {tradingView.strongest_momentum?.symbol??"No available candidate"}. Highest risk: {tradingView.highest_risk?.symbol??"No available candidate"}.</p><p className="mt-2 text-slate-500">{tradingView.disclaimer}</p></div>:<p className="mt-3 text-sm text-slate-500">Trading view is unavailable.</p>}</div>
    <div className="rounded-xl border bg-white p-5 lg:col-span-2"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Alerts ({alerts.filter(i=>!i.is_read).length})</h2><button className="text-sm underline" type="button" onClick={()=>void readAllAlerts()}>Mark all read</button></div>{alerts.length?<div className="mt-3 space-y-2 text-sm">{alerts.map(i=><button className="block w-full rounded border p-3 text-left" key={i.id} onClick={()=>void readAlert(i.id)} type="button"><strong>{i.severity}{i.symbol?` · ${i.symbol}`:""}</strong><p>{i.message}</p><span className="text-xs text-slate-500">{new Date(i.created_at).toLocaleString()} {i.is_read?"· Read":"· Unread"}</span></button>)}</div>:<p className="mt-3 text-sm text-slate-500">No alerts right now.</p>}</div>
    {error&&<p className="text-sm text-red-600 lg:col-span-2">{error}</p>}
  </section>;
}
