import { useEffect, useMemo, useState } from "react";

import { IntelligencePanel } from "../components/IntelligencePanel";
import StockSearch from "../components/StockSearch";
import { getPortfolioAnalytics, type PortfolioAnalytics } from "../services/analytics";
import { addWatchlistSymbol, deleteWatchlistSymbol, getWatchlistQuotes, type WatchlistQuote } from "../services/watchlist";

type DashboardPageProps = { onLogout: () => void; onTransactions: () => void };
function money(value: number | null | undefined) { return value == null ? "—" : value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function signed(value: number) { return `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`; }

function Sparkline({ positive }: { positive: boolean }) {
  return <svg viewBox="0 0 180 48" className="h-12 w-full" aria-hidden="true"><path d="M2 38 C24 35 27 24 46 29 S69 35 84 20 S108 28 124 14 S147 18 178 5" fill="none" stroke={positive ? "#35d399" : "#fb7185"} strokeWidth="2.5" strokeLinecap="round" /><path d="M2 48 L2 38 C24 35 27 24 46 29 S69 35 84 20 S108 28 124 14 S147 18 178 5 L178 48 Z" fill={positive ? "rgba(53,211,153,.08)" : "rgba(251,113,133,.08)"} /></svg>;
}

export default function DashboardPage({ onLogout, onTransactions }: DashboardPageProps) {
  const [analytics, setAnalytics] = useState<PortfolioAnalytics | null>(null);
  const [watchlist, setWatchlist] = useState<WatchlistQuote[]>([]);
  const [newSymbol, setNewSymbol] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function loadDashboard() {
    try { setLoading(true); setError(""); const [a, w] = await Promise.all([getPortfolioAnalytics(), getWatchlistQuotes()]); setAnalytics(a); setWatchlist(w); }
    catch (err) { setError(err instanceof Error ? err.message : "Unable to load dashboard."); }
    finally { setLoading(false); }
  }
  useEffect(() => { void loadDashboard(); }, []);
  async function addSymbol() { const symbol = newSymbol.trim(); if (!symbol) return; try { await addWatchlistSymbol(symbol); setNewSymbol(""); await loadDashboard(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to add symbol."); } }
  async function removeSymbol(id: number) { try { await deleteWatchlistSymbol(id); await loadDashboard(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to remove symbol."); } }

  if (loading) return <main className="tp-page"><div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i => <div key={i} className="h-32 animate-pulse rounded-2xl border border-white/10 bg-white/[.03]" />)}</div></main>;
  if (!analytics) return <main className="tp-page"><section className="tp-premium-card mx-auto max-w-xl rounded-2xl p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-red-400/10 text-red-300">!</div><h1 className="mt-4 text-2xl font-black text-white">Dashboard unavailable</h1><p className="mt-2 text-sm text-slate-500">We could not load your portfolio intelligence.</p>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<button type="button" onClick={() => void loadDashboard()} className="mt-5 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-bold text-white">Retry</button></section></main>;

  const profitPositive = analytics.total_profit_loss >= 0;
  const exposure = analytics.current_value > 0 ? Math.min(100, (analytics.total_invested / Math.max(analytics.current_value, 1)) * 100) : 0;
  const pulse = [...watchlist].filter(item => item.market_data_available && item.change_percent != null).sort((a,b) => Math.abs(b.change_percent ?? 0) - Math.abs(a.change_percent ?? 0)).slice(0, 5);
  const strongest = useMemo(() => [...watchlist].filter(x => x.market_data_available && x.change_percent != null).sort((a,b) => (b.change_percent ?? 0) - (a.change_percent ?? 0)).slice(0, 5), [watchlist]);

  return <main className="tp-page">
    <header className="flex flex-wrap items-end justify-between gap-5">
      <div><div className="tp-live-line">Paper environment · execution locked</div><h1 className="tp-page-title mt-2 text-4xl font-black">Market command center</h1><p className="tp-page-subtitle mt-2 max-w-2xl text-sm">A calm, information-dense view of your portfolio, watchlist pulse and current trading context.</p></div>
      <div className="flex gap-2"><button type="button" onClick={onTransactions} className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-2.5 text-xs font-bold text-slate-300 hover:border-white/20 hover:text-white">Ledger</button><button type="button" onClick={() => void loadDashboard()} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">Refresh</button><button type="button" onClick={onLogout} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-bold text-slate-400 hover:text-white">Sign out</button></div>
    </header>
    {error && <div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm font-semibold text-red-200">{error}</div>}
    {!analytics.market_data_complete && <div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/10 p-4 text-xs font-semibold text-amber-200">Market data incomplete for {analytics.unavailable_symbols.join(", ")}. Those values are not treated as live prices.</div>}

    <section className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {[{label:"Portfolio value",value:`₹${money(analytics.current_value)}`,meta:`Invested ₹${money(analytics.total_invested)}`},{label:"Total P/L",value:`${profitPositive?"+":""}₹${money(analytics.total_profit_loss)}`,meta:`${signed(analytics.total_return_percent)} return`,tone:profitPositive},{label:"Unrealized P/L",value:`${analytics.unrealized_profit_loss>=0?"+":""}₹${money(analytics.unrealized_profit_loss)}`,meta:`${analytics.holdings_count} open holdings`,tone:analytics.unrealized_profit_loss>=0},{label:"Transactions",value:String(analytics.transactions_count),meta:"Recorded portfolio activity"}].map(card => <article key={card.label} className="tp-kpi"><p className="tp-section-label">{card.label}</p><p className={`tp-number mt-3 text-2xl font-black ${card.tone == null ? "text-white" : card.tone ? "text-emerald-300" : "text-rose-300"}`}>{card.value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{card.meta}</p></article>)}
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_.9fr]">
      <article className="tp-premium-card overflow-hidden rounded-2xl">
        <div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="tp-section-label">Portfolio pulse</p><h2 className="mt-1 text-lg font-black text-white">Equity snapshot</h2></div><span className={`rounded-full px-3 py-1 text-[10px] font-extrabold ${profitPositive ? "bg-emerald-400/10 text-emerald-300" : "bg-rose-400/10 text-rose-300"}`}>{profitPositive ? "POSITIVE" : "UNDER PRESSURE"}</span></div>
        <div className="grid gap-5 p-5 md:grid-cols-[1fr_220px] md:items-center"><div><div className="flex items-end justify-between"><div><p className="text-4xl font-black tracking-tight text-white">₹{money(analytics.current_value)}</p><p className={`mt-1 text-sm font-bold ${profitPositive ? "text-emerald-300" : "text-rose-300"}`}>{profitPositive?"+":""}₹{money(analytics.total_profit_loss)} · {signed(analytics.total_return_percent)}</p></div><span className="tp-section-label">Current snapshot</span></div><div className="mt-6"><Sparkline positive={profitPositive} /></div><p className="mt-2 text-[11px] text-slate-600">Visualization is a terminal-style status cue; historical equity series are not fabricated when unavailable.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="tp-section-label">Exposure</p><p className="mt-2 text-3xl font-black text-white">{exposure.toFixed(0)}%</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-teal-400" style={{width:`${exposure}%`}} /></div><p className="mt-3 text-xs text-slate-500">Invested capital relative to current portfolio value.</p></div></div>
      </article>
      <article className="tp-premium-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="tp-section-label">Risk center</p><h2 className="mt-1 text-lg font-black text-white">Capital posture</h2></div><span className="grid h-8 w-8 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300">✓</span></div><div className="mt-6 space-y-4"><div className="flex items-center justify-between border-b border-white/5 pb-3"><span className="text-xs text-slate-500">Invested</span><b className="text-sm text-white">₹{money(analytics.total_invested)}</b></div><div className="flex items-center justify-between border-b border-white/5 pb-3"><span className="text-xs text-slate-500">Unrealized</span><b className={analytics.unrealized_profit_loss>=0?"text-sm text-emerald-300":"text-sm text-rose-300"}>₹{money(analytics.unrealized_profit_loss)}</b></div><div className="flex items-center justify-between"><span className="text-xs text-slate-500">Open holdings</span><b className="text-sm text-white">{analytics.holdings_count}</b></div></div><div className="mt-6 rounded-xl border border-emerald-400/10 bg-emerald-400/[.05] p-3 text-xs leading-5 text-emerald-100"><b>Safety:</b> dashboard analytics do not authorize live execution.</div></article>
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.9fr]">
      <article className="tp-premium-card rounded-2xl p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="tp-section-label">Opportunity radar</p><h2 className="mt-1 text-lg font-black text-white">Watchlist strongest movers</h2></div><span className="text-[10px] font-bold uppercase tracking-wider text-slate-600">Market pulse · not a trade signal</span></div><div className="mt-4 space-y-2">{strongest.length===0?<div className="rounded-xl bg-white/[.03] p-6 text-center text-sm text-slate-500">Add symbols to your watchlist to populate the radar.</div>:strongest.map((item,index)=><div key={item.id} className="grid grid-cols-[34px_1fr_auto] items-center gap-3 rounded-xl border border-white/5 bg-white/[.02] p-3 transition hover:border-violet-400/20 hover:bg-violet-400/[.03]"><span className="text-xs font-black text-slate-600">{String(index+1).padStart(2,"0")}</span><div><div className="flex items-center gap-2"><span className="font-black text-white">{item.symbol}</span><span className="text-[10px] font-bold text-slate-600">WATCHLIST</span></div><div className="mt-2 h-1.5 max-w-sm overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${item.change_percent!>=0?"bg-emerald-400":"bg-rose-400"}`} style={{width:`${Math.min(100,Math.max(8,Math.abs(item.change_percent!)*12))}%`}} /></div></div><div className={`text-right text-sm font-black ${item.change_percent!>=0?"text-emerald-300":"text-rose-300"}`}>{signed(item.change_percent!)}</div></div>)}</div></article>
      <article className="tp-premium-card rounded-2xl p-5"><div><p className="tp-section-label">Market pulse</p><h2 className="mt-1 text-lg font-black text-white">Highest movement</h2></div><div className="mt-4 space-y-3">{pulse.length===0?<p className="py-6 text-sm text-slate-500">No live watchlist quotes available.</p>:pulse.map(item=><div key={item.id} className="flex items-center justify-between"><div><p className="text-sm font-bold text-white">{item.symbol}</p><p className="text-[10px] text-slate-600">₹{money(item.price)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${item.change_percent!>=0?"bg-emerald-400/10 text-emerald-300":"bg-rose-400/10 text-rose-300"}`}>{signed(item.change_percent!)}</span></div>)}</div></article>
    </section>

    <section className="tp-premium-card mt-5 overflow-hidden rounded-2xl"><div className="flex flex-col gap-4 border-b border-white/10 p-5 md:flex-row md:items-center md:justify-between"><div><p className="tp-section-label">Portfolio</p><h2 className="mt-1 text-lg font-black text-white">Holdings performance</h2><p className="mt-1 text-xs text-slate-500">Current value and unrealized P/L from available market data.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-white/10 text-[10px] uppercase tracking-wider text-slate-600"><th className="px-5 py-3">Symbol</th><th>Qty</th><th>Avg buy</th><th>Price</th><th>Value</th><th>P/L</th><th>Return</th></tr></thead><tbody>{analytics.stocks.length===0?<tr><td colSpan={7} className="px-5 py-10 text-center text-sm text-slate-500">No holdings yet.</td></tr>:analytics.stocks.map(stock=>{const price=stock.quantity>0?stock.current_value/stock.quantity:0;const positive=stock.unrealized_profit_loss>=0;return <tr key={stock.symbol} className="border-b border-white/5"><td className="px-5 py-4 font-black text-white">{stock.symbol}</td><td>{stock.quantity}</td><td>₹{money(stock.invested_amount/stock.quantity)}</td><td className="font-bold text-slate-200">₹{money(price)}</td><td>₹{money(stock.current_value)}</td><td className={positive?"font-bold text-emerald-300":"font-bold text-rose-300"}>{positive?"+":""}₹{money(stock.unrealized_profit_loss)}</td><td className={positive?"font-bold text-emerald-300":"font-bold text-rose-300"}>{positive?"+":""}{stock.unrealized_profit_loss_percent.toFixed(2)}%</td></tr>})}</tbody></table></div></section>

    <section className="tp-premium-card mt-5 overflow-hidden rounded-2xl"><div className="flex flex-col gap-4 border-b border-white/10 p-5 md:flex-row md:items-center md:justify-between"><div><p className="tp-section-label">Watchlist</p><h2 className="mt-1 text-lg font-black text-white">Market watch</h2></div><div className="flex w-full max-w-md gap-2"><div className="flex-1"><StockSearch value={newSymbol} onChange={setNewSymbol} placeholder="Search TCS, Tata, Infosys..." /></div><button type="button" onClick={() => void addSymbol()} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white">Add</button></div></div>{watchlist.length===0?<div className="p-8 text-center text-sm text-slate-500">Your watchlist is empty.</div>:<div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4">{watchlist.map(item=>{const valid=item.market_data_available&&item.price!=null&&item.change_percent!=null;return <div key={item.id} className="rounded-xl border border-white/5 bg-white/[.02] p-4"><div className="flex items-center justify-between"><span className="font-black text-white">{item.symbol}</span><button type="button" onClick={()=>void removeSymbol(item.id)} className="text-[10px] font-bold text-slate-600 hover:text-rose-300">Remove</button></div>{valid?<><p className="tp-number mt-3 text-xl font-black text-white">₹{money(item.price)}</p><p className={`mt-1 text-xs font-black ${item.change_percent!>=0?"text-emerald-300":"text-rose-300"}`}>{signed(item.change_percent!)}</p></>:<p className="mt-3 text-xs font-semibold text-amber-300">Market data unavailable</p>}</div>})}</div>}</section>
    <div className="mt-5"><IntelligencePanel /></div>
  </main>;
}
