import { useEffect, useMemo, useState } from "react";
import StockSearch from "../components/StockSearch";
import { getPortfolioAnalytics, type PortfolioAnalytics } from "../services/analytics";
import { addWatchlistSymbol, deleteWatchlistSymbol, getWatchlistQuotes, type WatchlistQuote } from "../services/watchlist";

type Props = { onLogout: () => void; onTransactions: () => void };
const money=(v:number|null|undefined)=>v==null?"—":v.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const signed=(v:number)=>`${v>=0?"+":""}${v.toFixed(2)}%`;

export default function DashboardPageStable({onLogout,onTransactions}:Props){
 const [analytics,setAnalytics]=useState<PortfolioAnalytics|null>(null);
 const [watchlist,setWatchlist]=useState<WatchlistQuote[]>([]);
 const [newSymbol,setNewSymbol]=useState("");
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 const [refreshing,setRefreshing]=useState(false);
 const load=async()=>{try{setLoading(true);setError("");const [a,w]=await Promise.all([getPortfolioAnalytics(),getWatchlistQuotes()]);setAnalytics(a);setWatchlist(w);}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.");}finally{setLoading(false);setRefreshing(false);}};
 useEffect(()=>{void load();},[]);
 const strongest=useMemo(()=>watchlist.filter(x=>x.market_data_available&&x.change_percent!=null).sort((a,b)=>(b.change_percent??0)-(a.change_percent??0)).slice(0,5),[watchlist]);
 const pulse=useMemo(()=>watchlist.filter(x=>x.market_data_available&&x.change_percent!=null).sort((a,b)=>Math.abs(b.change_percent??0)-Math.abs(a.change_percent??0)).slice(0,5),[watchlist]);
 const add=async()=>{const s=newSymbol.trim();if(!s)return;try{await addWatchlistSymbol(s);setNewSymbol("");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to add symbol.");}};
 const remove=async(id:number)=>{try{await deleteWatchlistSymbol(id);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to remove symbol.");}};
 if(loading)return <main className="tp-page"><div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-32 animate-pulse rounded-2xl border border-white/10 bg-white/[.03]"/> )}</div></main>;
 if(!analytics)return <main className="tp-page"><section className="tp-premium-card mx-auto max-w-xl rounded-2xl p-8 text-center"><h1 className="text-2xl font-black text-white">Dashboard unavailable</h1><p className="mt-2 text-sm text-slate-500">{error||"Portfolio analytics could not be loaded."}</p><button type="button" onClick={()=>void load()} className="mt-5 rounded-xl bg-violet-500 px-5 py-2.5 text-sm font-bold text-white">Retry</button></section></main>;
 const positive=analytics.total_profit_loss>=0;
 const exposure=analytics.current_value>0?Math.min(100,(analytics.total_invested/Math.max(analytics.current_value,1))*100):0;
 return <main className="tp-page">
  <header className="flex flex-wrap items-end justify-between gap-5"><div><div className="tp-live-line">Paper environment · execution locked</div><h1 className="tp-page-title mt-2 text-4xl font-black">Market command center</h1><p className="tp-page-subtitle mt-2 max-w-2xl text-sm">Portfolio, watchlist and Indian-market context in one cockpit.</p></div><div className="flex gap-2"><button type="button" onClick={onTransactions} className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-2.5 text-xs font-bold text-slate-300">Ledger</button><button type="button" disabled={refreshing} onClick={()=>{setRefreshing(true);void load();}} className="rounded-xl bg-violet-500 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{refreshing?"Refreshing…":"Refresh"}</button><button type="button" onClick={onLogout} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-bold text-slate-400">Sign out</button></div></header>
  {error&&<div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
  {!analytics.market_data_complete&&<div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/10 p-4 text-xs font-semibold text-amber-200">Market data incomplete for {analytics.unavailable_symbols.join(", ")}.</div>}
  <section className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{l:"Portfolio value",v:`₹${money(analytics.current_value)}`,m:`Invested ₹${money(analytics.total_invested)}`},{l:"Total P/L",v:`${positive?"+":""}₹${money(analytics.total_profit_loss)}`,m:signed(analytics.total_return_percent),c:positive},{l:"Unrealized P/L",v:`${analytics.unrealized_profit_loss>=0?"+":""}₹${money(analytics.unrealized_profit_loss)}`,m:`${analytics.holdings_count} open holdings`,c:analytics.unrealized_profit_loss>=0},{l:"Transactions",v:String(analytics.transactions_count),m:"Recorded activity"}].map(x=><article key={x.l} className="tp-kpi"><p className="tp-section-label">{x.l}</p><p className={`mt-3 text-2xl font-black ${x.c==null?"text-white":x.c?"text-emerald-300":"text-rose-300"}`}>{x.v}</p><p className="mt-1 text-xs text-slate-500">{x.m}</p></article>)}</section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_.9fr]"><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Portfolio pulse</p><div className="mt-2 flex items-end justify-between"><div><h2 className="text-3xl font-black text-white">₹{money(analytics.current_value)}</h2><p className={positive?"text-sm font-bold text-emerald-300":"text-sm font-bold text-rose-300"}>{positive?"+":""}₹{money(analytics.total_profit_loss)} · {signed(analytics.total_return_percent)}</p></div><span className="tp-section-label">Current snapshot</span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-violet-500 to-teal-400" style={{width:`${exposure}%`}}/></div><p className="mt-2 text-xs text-slate-500">Capital exposure {exposure.toFixed(0)}%</p></article><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Risk center</p><h2 className="mt-1 text-lg font-black text-white">Capital posture</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Invested</span><b className="text-white">₹{money(analytics.total_invested)}</b></div><div className="flex justify-between"><span className="text-slate-500">Unrealized</span><b className="text-white">₹{money(analytics.unrealized_profit_loss)}</b></div><div className="flex justify-between"><span className="text-slate-500">Open holdings</span><b className="text-white">{analytics.holdings_count}</b></div></div></article></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Opportunity radar</p><h2 className="mt-1 text-lg font-black text-white">Watchlist strongest movers</h2><div className="mt-4 space-y-2">{strongest.length===0?<p className="rounded-xl bg-white/[.03] p-6 text-sm text-slate-500">Add Indian stocks to your watchlist to populate this view.</p>:strongest.map((x,i)=><div key={x.id} className="flex items-center justify-between rounded-xl border border-white/5 bg-white/[.02] p-3"><span className="text-xs text-slate-600">{String(i+1).padStart(2,"0")}</span><b className="flex-1 px-3 text-white">{x.symbol}</b><span className={x.change_percent!>=0?"text-emerald-300":"text-rose-300"}>{signed(x.change_percent!)}</span></div>)}</div></article><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Market pulse</p><h2 className="mt-1 text-lg font-black text-white">Highest movement</h2><div className="mt-4 space-y-3">{pulse.length===0?<p className="text-sm text-slate-500">No live watchlist quotes available.</p>:pulse.map(x=><div key={x.id} className="flex justify-between"><span className="text-sm font-bold text-white">{x.symbol}</span><span className={x.change_percent!>=0?"text-emerald-300":"text-rose-300"}>{signed(x.change_percent!)}</span></div>)}</div></article></section>
  <section className="tp-premium-card mt-5 overflow-hidden rounded-2xl"><div className="border-b border-white/10 p-5"><p className="tp-section-label">Portfolio</p><h2 className="mt-1 text-lg font-black text-white">Holdings performance</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b border-white/10 text-[10px] uppercase tracking-wider text-slate-600"><th className="px-5 py-3">Symbol</th><th>Qty</th><th>Avg buy</th><th>Price</th><th>Value</th><th>P/L</th><th>Return</th></tr></thead><tbody>{analytics.stocks.length===0?<tr><td colSpan={7} className="px-5 py-10 text-center text-slate-500">No holdings yet.</td></tr>:analytics.stocks.map(s=>{const price=s.quantity>0?s.current_value/s.quantity:0;const p=s.unrealized_profit_loss>=0;return <tr key={s.symbol} className="border-b border-white/5"><td className="px-5 py-4 font-black text-white">{s.symbol}</td><td>{s.quantity}</td><td>₹{money(s.invested_amount/s.quantity)}</td><td>₹{money(price)}</td><td>₹{money(s.current_value)}</td><td className={p?"text-emerald-300":"text-rose-300"}>{p?"+":""}₹{money(s.unrealized_profit_loss)}</td><td className={p?"text-emerald-300":"text-rose-300"}>{p?"+":""}{s.unrealized_profit_loss_percent.toFixed(2)}%</td></tr>})}</tbody></table></div></section>
  <section className="tp-premium-card mt-5 rounded-2xl p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="tp-section-label">Watchlist</p><h2 className="mt-1 text-lg font-black text-white">Market watch</h2></div><div className="flex gap-2"><div className="min-w-[260px]"><StockSearch value={newSymbol} onChange={setNewSymbol} onSelect={x=>setNewSymbol(x.symbol)} placeholder="Search Indian stock..."/></div><button type="button" onClick={()=>void add()} className="rounded-xl bg-violet-500 px-4 py-2 text-xs font-black text-white">Add</button></div></div><div className="mt-4 grid gap-2 md:grid-cols-2">{watchlist.length===0?<p className="rounded-xl bg-white/[.03] p-5 text-sm text-slate-500 md:col-span-2">Your watchlist is empty.</p>:watchlist.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border border-white/5 p-3"><div><b className="text-white">{x.symbol}</b><p className="text-xs text-slate-500">{x.market_data_available&&x.price!=null?`₹${money(x.price)} · ${signed(x.change_percent??0)}`:"Market data unavailable"}</p></div><button type="button" onClick={()=>void remove(x.id)} className="text-xs font-bold text-slate-500 hover:text-rose-300">Remove</button></div>)}</div></section>
 </main>;
}
