import { useEffect, useState } from "react";
import { autoScanFNO, getFNOPaperPositions, openFNOPaper, searchFNOUnderlyings, type FNOPaperPosition, type FNOUnderlying } from "../services/fno";

export default function FNOPage(){
 const [q,setQ]=useState("NIFTY"),[underlyings,setUnderlyings]=useState<FNOUnderlying[]>([]),[selected,setSelected]=useState<FNOUnderlying|null>(null);
 const [capital,setCapital]=useState("100000"),[interval,setIntervalValue]=useState<"1"|"5"|"15">("5"),[decision,setDecision]=useState<any>(null),[positions,setPositions]=useState<FNOPaperPosition[]>([]);
 const [marketConnected,setMarketConnected]=useState(false),[loading,setLoading]=useState(false),[opening,setOpening]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;const t=setTimeout(async()=>{try{const r=await searchFNOUnderlyings(q);if(live)setUnderlyings(r)}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to search NSE F&O underlyings")}},250);return()=>{live=false;clearTimeout(t)}},[q]);
 useEffect(()=>{const poll=async()=>{try{const r=await getFNOPaperPositions();setPositions(r.positions);setMarketConnected(r.market_connected);if(r.positions.some(p=>p.status!=="OPEN"))setMessage("A paper option position reached its exit condition.")}catch{setMarketConnected(false)}};void poll();const id=window.setInterval(()=>void poll(),3000);return()=>window.clearInterval(id)},[]);
 function choose(item:FNOUnderlying){setSelected(item);setQ(item.symbol);setDecision(null);setError("");setMessage("")}
 async function run(){if(!selected){setError("Select an NSE F&O underlying first.");return}const funds=Number(capital);if(!Number.isFinite(funds)||funds<=0){setError("Enter valid paper capital.");return}setLoading(true);setError("");setMessage("");setDecision(null);try{const r=await autoScanFNO({underlying_security_id:Number(selected.security_id),underlying_segment:selected.exchange_segment,symbol:selected.symbol,capital:funds,interval});setDecision(r.decision);if(r.decision.decision!=="QUALIFIED")setMessage(`No trade: ${r.decision.reason}`)}catch(e){setError(e instanceof Error?e.message:"Autonomous F&O analysis failed")}finally{setLoading(false)}}
 async function paperBuy(){if(!decision||decision.decision!=="QUALIFIED")return;setOpening(true);setError("");setMessage("");try{const r=await openFNOPaper(decision);setMessage(`Paper BUY opened: ${r.position.underlying} ${r.position.strike} ${r.position.option_type} · ${r.position.quantity} qty`);const p=await getFNOPaperPositions();setPositions(p.positions);setMarketConnected(p.market_connected)}catch(e){setError(e instanceof Error?e.message:"Unable to open paper option position")}finally{setOpening(false)}}
 return <main className="tp-page"><div className="tp-live-line">F&O command center · autonomous paper-only algorithm</div>
 <header className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="tp-page-title text-4xl font-black">Options Paper Trading</h1><p className="tp-page-subtitle mt-2 max-w-3xl">TradePilot decides the market direction, expiry, CE/PE, strike, lot size, entry, stop, target and risk/reward. No manual trade selection is used.</p></div><div className="flex gap-2"><span className="rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1.5 text-[10px] font-black text-amber-300">PAPER ONLY</span>{marketConnected&&<span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-black text-emerald-300">● LIVE LTP</span>}</div></header>
 {error&&<div className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm font-semibold text-rose-200">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm font-semibold text-emerald-200">{message}</div>}
 <section className="mt-7 grid gap-5 xl:grid-cols-[.85fr_1.5fr]"><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Algorithm inputs</p><div className="relative mt-3"><input value={q} onChange={e=>{setQ(e.target.value.toUpperCase());setSelected(null)}} placeholder="Search NIFTY, BANKNIFTY…" className="w-full rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm font-bold text-white outline-none"/>{!selected&&underlyings.length>0&&<div className="absolute left-0 right-0 top-14 z-10 rounded-xl border border-white/10 bg-slate-950 p-1 shadow-2xl">{underlyings.slice(0,8).map(x=><button key={x.security_id} onClick={()=>choose(x)} className="w-full rounded-lg px-3 py-2 text-left hover:bg-white/5"><b className="text-white">{x.symbol}</b><span className="ml-2 text-xs text-slate-500">{x.name}</span></button>)}</div>}</div>
 <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Paper capital<input value={capital} onChange={e=>setCapital(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-white"/></label><label className="text-xs font-bold text-slate-500">Analysis interval<select value={interval} onChange={e=>setIntervalValue(e.target.value as "1"|"5"|"15")} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-white"><option value="1">1 min</option><option value="5">5 min</option><option value="15">15 min</option></select></label></div>
 <button disabled={loading||!selected} onClick={()=>void run()} className="mt-5 w-full rounded-xl bg-violet-500 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{loading?"Analyzing market…":"RUN AUTONOMOUS ANALYSIS"}</button>
 <div className="mt-5 rounded-xl border border-white/5 bg-white/[.03] p-4"><p className="tp-section-label">System decides</p><div className="mt-3 grid gap-2 text-xs text-slate-400"><span>✓ Direction from completed underlying candles</span><span>✓ Nearest valid expiry</span><span>✓ CE/PE and strike from liquidity + Greeks</span><span>✓ Exchange lot size from instrument master</span><span>✓ Volatility-aware stop and target</span><span>✓ Risk-budget and capital-constrained quantity</span><span>✓ Risk/reward gate after estimated costs</span></div></div></article>
 <article className="tp-premium-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="tp-section-label">Algorithm decision</p><h2 className="mt-1 text-lg font-black text-white">No manual strike selection</h2></div>{decision&&<span className={`rounded-full px-3 py-1 text-[10px] font-black ${decision.decision==="QUALIFIED"?"bg-emerald-400/10 text-emerald-300":"bg-rose-400/10 text-rose-300"}`}>{decision.decision}</span>}</div>
 {!decision?<div className="mt-8 rounded-xl bg-white/[.03] p-10 text-center text-sm text-slate-500">Select an underlying and run autonomous analysis. The system will either produce a complete paper trade plan or explicitly return NO_TRADE.</div>:<div className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-4">{[["Direction",decision.direction], ["Confidence",`${decision.direction_confidence}%`],["Expiry",decision.underlying?.expiry||"—"],["Bars",String(decision.completed_bars??"—")]].map(([label,value])=><div key={label} className="rounded-xl bg-white/[.03] p-4"><p className="tp-section-label">{label}</p><p className="mt-2 font-black text-white">{value}</p></div>)}</div>{decision.contract&&<div className="rounded-xl border border-violet-400/20 bg-violet-400/[.05] p-5"><div className="grid gap-4 sm:grid-cols-4"><div><p className="tp-section-label">Contract</p><b className="text-xl text-white">{decision.contract.strike} {decision.contract.option_type}</b></div><div><p className="tp-section-label">Entry</p><b className="text-white">₹{decision.entry}</b></div><div><p className="tp-section-label">Stop / Target</p><b className="text-white">₹{decision.stop} / ₹{decision.target}</b></div><div><p className="tp-section-label">Quantity</p><b className="text-white">{decision.quantity} ({decision.lots} lots)</b></div></div><div className="mt-4 grid gap-3 sm:grid-cols-4 text-xs"><span>Risk ₹{decision.risk_amount}</span><span>Reward ₹{decision.reward_amount}</span><span>R:R {decision.risk_reward}</span><span>Capital ₹{decision.position_capital}</span></div>{(decision.estimated_stop_costs||decision.estimated_target_costs)&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-950/60 p-3 text-xs text-slate-400">Estimated costs at stop <b className="text-white">₹{decision.estimated_stop_costs?.total??"—"}</b></div><div className="rounded-lg bg-slate-950/60 p-3 text-xs text-slate-400">Estimated costs at target <b className="text-white">₹{decision.estimated_target_costs?.total??"—"}</b></div></div>}{decision.decision==="QUALIFIED"&&<button disabled={opening} onClick={()=>void paperBuy()} className="mt-5 w-full rounded-xl bg-emerald-500 px-4 py-3 text-sm font-black text-slate-950 disabled:opacity-40">{opening?"Opening virtual position…":"PAPER BUY · ALGORITHM APPROVED"}</button>}</div>}<div className="rounded-xl bg-slate-950/60 p-4"><p className="tp-section-label">Why this direction</p><p className="mt-2 text-sm text-slate-300">{(decision.direction_reasons||[decision.reason||"No trade"]).join(" · ")}</p></div></div>}
 </article></section>
 <section className="mt-5 tp-premium-card rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="tp-section-label">Live paper positions</p><h2 className="mt-1 text-lg font-black text-white">Option positions · marked every 3 seconds</h2></div><span className="text-xs font-bold text-slate-500">Virtual only · net P&L</span></div>{!positions.length?<p className="mt-6 rounded-xl bg-white/[.03] p-8 text-center text-sm text-slate-500">No open option paper positions.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="py-3">Contract</th><th>Expiry</th><th>Qty</th><th>Entry</th><th>LTP</th><th>SL</th><th>Target</th><th>P&L</th><th>Costs</th><th>Status</th></tr></thead><tbody>{positions.map(p=><tr key={p.id} className="border-t border-white/5"><td className="py-3 font-black text-white">{p.underlying} {p.strike} {p.option_type}</td><td>{p.expiry}</td><td>{p.quantity}</td><td>₹{p.entry_price.toFixed(2)}</td><td>{p.last_price==null?"—":`₹${p.last_price.toFixed(2)}`}</td><td>₹{p.stop_price.toFixed(2)}</td><td>₹{p.target_price.toFixed(2)}</td><td className={p.pnl>=0?"font-black text-emerald-300":"font-black text-rose-300"}>₹{p.pnl.toFixed(2)}</td><td>₹{p.estimated_round_trip_costs?.total?.toFixed(2)??"—"}</td><td>{p.status}</td></tr>)}</tbody></table></div>}</section>
 </main>;
}
