import { useEffect, useRef, useState } from "react";
import { autoScanFNO, getFNOPaperPositions, openFNOPaper, searchFNOUnderlyings, type FNOPaperPosition, type FNOUnderlying } from "../services/fno";

const DEFAULT_NIFTY: FNOUnderlying={security_id:"13",exchange_segment:"IDX_I",symbol:"NIFTY",name:"Nifty 50"};

export default function FNOPage(){
 const [q,setQ]=useState("NIFTY"),[underlyings,setUnderlyings]=useState<FNOUnderlying[]>([DEFAULT_NIFTY]),[selected,setSelected]=useState<FNOUnderlying|null>(DEFAULT_NIFTY);
 const [capital,setCapital]=useState("100000"),[interval,setIntervalValue]=useState<"1"|"5"|"15">("5"),[decision,setDecision]=useState<any>(null),[positions,setPositions]=useState<FNOPaperPosition[]>([]);
 const [marketConnected,setMarketConnected]=useState(false),[loading,setLoading]=useState(false),[opening,setOpening]=useState(false),[searching,setSearching]=useState(false),[showSuggestions,setShowSuggestions]=useState(false),[monitoring,setMonitoring]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const timerRef=useRef<number|null>(null); const sessionRef=useRef(false); const scanningRef=useRef(false);

 useEffect(()=>{let live=true;const t=setTimeout(async()=>{setSearching(true);try{const r=await searchFNOUnderlyings(q);if(!live)return;setUnderlyings(r.length?r:[DEFAULT_NIFTY]);setShowSuggestions(true);const exact=r.find(x=>x.symbol.toUpperCase()===q.trim().toUpperCase());if(exact)setSelected(exact);else if(q.trim().toUpperCase()!=="NIFTY")setSelected(null);setError("")}catch(e){if(!live)return;setError(e instanceof Error?e.message:"Unable to load NSE F&O underlyings")}finally{if(live)setSearching(false)}},300);return()=>{live=false;clearTimeout(t)}},[q]);
 useEffect(()=>{const poll=async()=>{try{const r=await getFNOPaperPositions();setPositions(r.positions);setMarketConnected(r.market_connected);if(r.positions.some(p=>p.status!=="OPEN"))setMessage("A paper option position reached its exit condition.")}catch{setMarketConnected(false)}};void poll();const id=window.setInterval(()=>void poll(),3000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>()=>{sessionRef.current=false;if(timerRef.current!==null)window.clearTimeout(timerRef.current)},[]);
 function choose(item:FNOUnderlying){sessionRef.current=false;if(timerRef.current!==null)window.clearTimeout(timerRef.current);setMonitoring(false);setSelected(item);setQ(item.symbol);setDecision(null);setError("");setMessage("");setShowSuggestions(false)}
 function nextScanDelay(){const minutes=Number(interval);const now=new Date();const next=new Date(now);next.setSeconds(5,0);const nextBucket=Math.floor(now.getMinutes()/minutes)*minutes+minutes;next.setMinutes(nextBucket);const delay=next.getTime()-now.getTime();return Math.max(5000,Math.min(delay,minutes*60*1000+10000))}
 async function scanOnce(autoOpen=true){if(!selected||scanningRef.current||!sessionRef.current)return;scanningRef.current=true;setLoading(true);setError("");try{const funds=Number(capital);if(!Number.isFinite(funds)||funds<=0){sessionRef.current=false;setMonitoring(false);setError("Enter valid paper capital.");return}const r=await autoScanFNO({underlying_security_id:Number(selected.security_id),underlying_segment:selected.exchange_segment,symbol:selected.symbol,capital:funds,interval});const next=r.decision;setDecision(next);if(next.decision==="QUALIFIED"){setMessage("Trade qualified. TradePilot is opening the virtual position automatically.");if(autoOpen){setOpening(true);try{const opened=await openFNOPaper(next);setMessage(`PAPER TRADE OPENED: ${opened.position.underlying} ${opened.position.strike} ${opened.position.option_type} · ${opened.position.quantity} qty. No broker order sent.`);sessionRef.current=false;setMonitoring(false);if(timerRef.current!==null)window.clearTimeout(timerRef.current);const p=await getFNOPaperPositions();setPositions(p.positions);setMarketConnected(p.market_connected)}catch(e){setError(e instanceof Error?e.message:"Unable to open paper option position")}finally{setOpening(false)}}}else{setMessage(next.reason==="INSUFFICIENT_COMPLETED_BARS"?`Waiting for enough completed ${interval}-minute candles. TradePilot will keep monitoring and will not force a trade.`:`No trade yet: ${next.reason}. TradePilot will wait for the next completed ${interval}-minute candle.`)}}catch(e){const text=e instanceof Error?e.message:"Autonomous F&O analysis failed";setError(text);if(/401|authentication|token invalid|expired/i.test(text)){sessionRef.current=false;setMonitoring(false);setMessage("")}}finally{scanningRef.current=false;setLoading(false)}}
 function scheduleNextScan(){if(!sessionRef.current)return;if(timerRef.current!==null)window.clearTimeout(timerRef.current);timerRef.current=window.setTimeout(async()=>{await scanOnce(true);scheduleNextScan()},nextScanDelay())}
 async function startSession(){if(!selected){setError("Select an NSE F&O underlying first.");setShowSuggestions(true);return}const funds=Number(capital);if(!Number.isFinite(funds)||funds<=0){setError("Enter valid paper capital.");return}sessionRef.current=true;setMonitoring(true);setDecision(null);setError("");setMessage(`AUTONOMOUS SESSION ACTIVE: waiting for a qualified ${selected.symbol} setup. TradePilot will not force a trade.`);await scanOnce(true);scheduleNextScan()}
 function stopSession(){sessionRef.current=false;if(timerRef.current!==null)window.clearTimeout(timerRef.current);setMonitoring(false);setLoading(false);setMessage("Autonomous monitoring stopped. No new paper trade will be opened.")}
 return <main className="tp-page"><div className="tp-live-line">F&O command center · autonomous paper-only algorithm</div>
 <header className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="tp-page-title text-4xl font-black">Options Paper Trading</h1><p className="tp-page-subtitle mt-2 max-w-3xl">TradePilot decides the market direction, expiry, CE/PE, strike, lot size, entry, stop, target and risk/reward. No manual trade selection is used.</p></div><div className="flex gap-2"><span className="rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1.5 text-[10px] font-black text-amber-300">PAPER ONLY</span>{monitoring&&<span className="rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1.5 text-[10px] font-black text-cyan-300">● WAITING FOR TRADE</span>}{marketConnected&&<span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-black text-emerald-300">● LIVE LTP</span>}</div></header>
 {error&&<div className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm font-semibold text-rose-200">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm font-semibold text-emerald-200">{message}</div>}
 <section className="mt-7 grid gap-5 xl:grid-cols-[.85fr_1.5fr]"><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Algorithm inputs</p><div className="relative mt-3"><input value={q} disabled={monitoring} onFocus={()=>setShowSuggestions(true)} onChange={e=>{setQ(e.target.value.toUpperCase());setSelected(null);setShowSuggestions(true)}} placeholder="Search NIFTY, BANKNIFTY, RELIANCE…" className="w-full rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm font-bold text-white outline-none disabled:opacity-60"/>{showSuggestions&&!monitoring&&<div className="absolute left-0 right-0 top-14 z-20 max-h-72 overflow-y-auto rounded-xl border border-white/10 bg-slate-950 p-1 shadow-2xl">{searching&&<div className="px-3 py-3 text-xs font-semibold text-slate-500">Loading NSE F&O symbols…</div>}{!searching&&!underlyings.length&&<div className="px-3 py-3 text-xs font-semibold text-slate-500">No matching NSE F&O symbol found.</div>}{!searching&&underlyings.map(x=><button key={`${x.exchange_segment}-${x.security_id}`} onClick={()=>choose(x)} className={`w-full rounded-lg px-3 py-2 text-left ${selected?.security_id===x.security_id?"bg-violet-500/15":"hover:bg-white/5"}`}><b className="text-white">{x.symbol}</b><span className="ml-2 text-xs text-slate-500">{x.name}</span></button>)}</div>}</div>
 <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Paper capital<input disabled={monitoring} value={capital} onChange={e=>setCapital(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-white disabled:opacity-60"/></label><label className="text-xs font-bold text-slate-500">Analysis interval<select disabled={monitoring} value={interval} onChange={e=>setIntervalValue(e.target.value as "1"|"5"|"15")} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-white disabled:opacity-60"><option value="1">1 min</option><option value="5">5 min</option><option value="15">15 min</option></select></label></div>
 {!monitoring?<button disabled={loading||opening||!selected} onClick={()=>void startSession()} className="mt-5 w-full rounded-xl bg-violet-500 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{loading?"Analyzing market…":"START AUTONOMOUS PAPER SESSION"}</button>:<button disabled={loading||opening} onClick={stopSession} className="mt-5 w-full rounded-xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm font-black text-rose-200 disabled:opacity-50">{loading?"Finishing current scan…":"STOP AUTONOMOUS SESSION"}</button>}
 <div className="mt-5 rounded-xl border border-white/5 bg-white/[.03] p-4"><p className="tp-section-label">System decides and waits</p><div className="mt-3 grid gap-2 text-xs text-slate-400"><span>✓ Direction from completed underlying candles</span><span>✓ Waits for a valid confidence gate</span><span>✓ Chooses expiry, CE/PE and strike automatically</span><span>✓ Calculates exchange lot size automatically</span><span>✓ Calculates entry, volatility-aware stop and target</span><span>✓ Enforces risk budget and cost-aware risk/reward</span><span>✓ Opens a virtual position automatically only after QUALIFIED</span><span>✓ Otherwise waits for the next completed candle — never forces a trade</span></div></div></article>
 <article className="tp-premium-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="tp-section-label">Algorithm decision</p><h2 className="mt-1 text-lg font-black text-white">{monitoring?"Waiting for a qualified setup":"No manual strike selection"}</h2></div>{decision&&<span className={`rounded-full px-3 py-1 text-[10px] font-black ${decision.decision==="QUALIFIED"?"bg-emerald-400/10 text-emerald-300":"bg-rose-400/10 text-rose-300"}`}>{decision.decision}</span>}</div>
 {!decision?<div className="mt-8 rounded-xl bg-white/[.03] p-10 text-center text-sm text-slate-500">Start the autonomous session. TradePilot will monitor completed candles and either produce a complete paper trade plan or keep waiting.</div>:<div className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-4">{[["Direction",decision.direction], ["Confidence",`${decision.direction_confidence}%`],["Expiry",decision.underlying?.expiry||"—"],["Bars",String(decision.completed_bars??"—")]].map(([label,value])=><div key={label} className="rounded-xl bg-white/[.03] p-4"><p className="tp-section-label">{label}</p><p className="mt-2 font-black text-white">{value}</p></div>)}</div>{decision.contract&&<div className="rounded-xl border border-violet-400/20 bg-violet-400/[.05] p-5"><div className="grid gap-4 sm:grid-cols-4"><div><p className="tp-section-label">Contract</p><b className="text-xl text-white">{decision.contract.strike} {decision.contract.option_type}</b></div><div><p className="tp-section-label">Entry</p><b className="text-white">₹{decision.entry}</b></div><div><p className="tp-section-label">Stop / Target</p><b className="text-white">₹{decision.stop} / ₹{decision.target}</b></div><div><p className="tp-section-label">Quantity</p><b className="text-white">{decision.quantity} ({decision.lots} lots)</b></div></div><div className="mt-4 grid gap-3 sm:grid-cols-4 text-xs"><span>Risk ₹{decision.risk_amount}</span><span>Reward ₹{decision.reward_amount}</span><span>R:R {decision.risk_reward}</span><span>Capital ₹{decision.position_capital}</span></div></div>}{decision.decision!=="QUALIFIED"&&<div className="rounded-xl bg-slate-950/60 p-4"><p className="tp-section-label">Why no trade yet</p><p className="mt-2 text-sm text-slate-300">{(decision.direction_reasons||[decision.reason||"No trade"]).join(" · ")}</p></div>}</div>}
 </article></section>
 <section className="mt-5 tp-premium-card rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="tp-section-label">Live paper positions</p><h2 className="mt-1 text-lg font-black text-white">Option positions · marked every 3 seconds</h2></div><span className="text-xs font-bold text-slate-500">Virtual only · net P&L</span></div>{!positions.length?<p className="mt-6 rounded-xl bg-white/[.03] p-8 text-center text-sm text-slate-500">No open option paper positions.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="py-3">Contract</th><th>Expiry</th><th>Qty</th><th>Entry</th><th>LTP</th><th>SL</th><th>Target</th><th>P&L</th><th>Costs</th><th>Status</th></tr></thead><tbody>{positions.map(p=><tr key={p.id} className="border-t border-white/5"><td className="py-3 font-black text-white">{p.underlying} {p.strike} {p.option_type}</td><td>{p.expiry}</td><td>{p.quantity}</td><td>₹{p.entry_price.toFixed(2)}</td><td>{p.last_price==null?"—":`₹${p.last_price.toFixed(2)}`}</td><td>₹{p.stop_price.toFixed(2)}</td><td>₹{p.target_price.toFixed(2)}</td><td className={p.pnl>=0?"font-black text-emerald-300":"font-black text-rose-300"}>₹{p.pnl.toFixed(2)}</td><td>₹{p.estimated_round_trip_costs?.total?.toFixed(2)??"—"}</td><td>{p.status}</td></tr>)}</tbody></table></div>}</section>
 </main>;
}
