import { useEffect, useState } from "react";
import { getFNOChain, getFNOExpiries, getFNOPaperPositions, openFNOPaper, scanFNO, searchFNOUnderlyings, type FNOCandidate, type FNOPaperPosition, type FNOUnderlying } from "../services/fno";

export default function FNOPage(){
 const [q,setQ]=useState("NIFTY");
 const [underlyings,setUnderlyings]=useState<FNOUnderlying[]>([]);
 const [selected,setSelected]=useState<FNOUnderlying|null>(null);
 const [expiries,setExpiries]=useState<string[]>([]);
 const [expiry,setExpiry]=useState("");
 const [direction,setDirection]=useState<"BULLISH"|"BEARISH">("BULLISH");
 const [capital,setCapital]=useState("100000");
 const [lotSize,setLotSize]=useState("1");
 const [candidates,setCandidates]=useState<FNOCandidate[]>([]);
 const [decision,setDecision]=useState<any>(null);
 const [positions,setPositions]=useState<FNOPaperPosition[]>([]);
 const [marketConnected,setMarketConnected]=useState(false);
 const [loading,setLoading]=useState(false);
 const [opening,setOpening]=useState(false);
 const [error,setError]=useState("");
 const [message,setMessage]=useState("");

 useEffect(()=>{let live=true;const t=setTimeout(async()=>{try{const r=await searchFNOUnderlyings(q);if(live)setUnderlyings(r)}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to search F&O underlyings")}},250);return()=>{live=false;clearTimeout(t)}},[q]);
 useEffect(()=>{const poll=async()=>{try{const r=await getFNOPaperPositions();setPositions(r.positions);setMarketConnected(r.market_connected);if(r.positions.some(p=>p.status!=="OPEN"))setMessage("A paper option position reached its exit condition.")}catch{setMarketConnected(false)}};void poll();const id=window.setInterval(()=>void poll(),3000);return()=>window.clearInterval(id)},[]);

 async function choose(item:FNOUnderlying){setSelected(item);setQ(item.symbol);setError("");setMessage("");try{const r=await getFNOExpiries(Number(item.security_id),item.exchange_segment);const list=r?.data??r;setExpiries(Array.isArray(list)?list:[]);setExpiry(Array.isArray(list)&&list.length?list[0]:"")}catch(e){setError(e instanceof Error?e.message:"Unable to load expiries")}}
 async function run(){if(!selected||!expiry){setError("Select an NSE F&O underlying and expiry.");return}const lots=Number(lotSize);if(!Number.isInteger(lots)||lots<=0){setError("Enter a valid lot size.");return}setLoading(true);setError("");setMessage("");try{const chain=await getFNOChain(Number(selected.security_id),selected.exchange_segment,expiry);const r=await scanFNO({underlying:{symbol:selected.symbol,name:selected.name,security_id:selected.security_id,capital:Number(capital),lot_size:lots,expiry},direction,option_chain:chain?.data??chain});setCandidates(r.candidates);setDecision(r.decision)}catch(e){setError(e instanceof Error?e.message:"F&O scan failed")}finally{setLoading(false)}}
 async function paperBuy(){if(!decision||decision.decision!=="QUALIFIED")return;setOpening(true);setError("");setMessage("");try{const r=await openFNOPaper(decision);setMessage(`Paper BUY opened: ${r.position.underlying} ${r.position.strike} ${r.position.option_type} · ${r.position.quantity} qty at ₹${r.position.entry_price.toFixed(2)}`);const p=await getFNOPaperPositions();setPositions(p.positions);setMarketConnected(p.market_connected)}catch(e){setError(e instanceof Error?e.message:"Unable to open paper option position")}finally{setOpening(false)}}

 return <main className="tp-page"><div className="tp-live-line">F&O command center · paper-only decision engine</div>
 <header className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="tp-page-title text-4xl font-black">Options Paper Trading</h1><p className="tp-page-subtitle mt-2 max-w-3xl">Live NSE option-chain analysis through Dhan, followed by a virtual CE/PE BUY. No broker order is sent.</p></div><div className="flex gap-2"><span className="rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1.5 text-[10px] font-black text-amber-300">PAPER ONLY</span>{marketConnected&&<span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-black text-emerald-300">● LIVE LTP</span>}</div></header>
 {error&&<div className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm font-semibold text-rose-200">{error}</div>}
 {message&&<div className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm font-semibold text-emerald-200">{message}</div>}

 <section className="mt-7 grid gap-5 xl:grid-cols-[.9fr_1.5fr]"><article className="tp-premium-card rounded-2xl p-5"><p className="tp-section-label">Option setup</p><div className="relative mt-3"><input value={q} onChange={e=>{setQ(e.target.value);setSelected(null)}} placeholder="Search NIFTY, BANKNIFTY…" className="w-full rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm font-bold text-white outline-none"/>{!selected&&underlyings.length>0&&<div className="absolute left-0 right-0 top-14 z-10 rounded-xl border border-white/10 bg-slate-950 p-1 shadow-2xl">{underlyings.slice(0,8).map(x=><button key={x.security_id} onClick={()=>void choose(x)} className="w-full rounded-lg px-3 py-2 text-left hover:bg-white/5"><b className="text-white">{x.symbol}</b><span className="ml-2 text-xs text-slate-500">{x.name}</span></button>)}</div>}</div>
 <div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setDirection("BULLISH")} className={`rounded-xl px-3 py-2 text-xs font-black ${direction==="BULLISH"?"bg-emerald-400/15 text-emerald-300":"bg-white/5 text-slate-500"}`}>CALL / BULLISH</button><button onClick={()=>setDirection("BEARISH")} className={`rounded-xl px-3 py-2 text-xs font-black ${direction==="BEARISH"?"bg-rose-400/15 text-rose-300":"bg-white/5 text-slate-500"}`}>PUT / BEARISH</button></div>
 <label className="mt-4 block text-xs font-bold text-slate-500">Expiry</label><select value={expiry} onChange={e=>setExpiry(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm font-bold text-white"><option value="">Select expiry</option>{expiries.map(x=><option key={x}>{x}</option>)}</select>
 <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Capital<input value={capital} onChange={e=>setCapital(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-white"/></label><label className="text-xs font-bold text-slate-500">Lot size<input value={lotSize} onChange={e=>setLotSize(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-white"/></label></div>
 <button disabled={loading} onClick={()=>void run()} className="mt-5 w-full rounded-xl bg-violet-500 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{loading?"Reading option chain…":"Scan options"}</button>
 <p className="mt-3 text-[11px] leading-5 text-slate-500">The scanner filters liquidity, OI, spread, IV and Delta. The paper BUY uses the qualified contract's ask/LTP and the calculated risk levels.</p></article>

 <article className="tp-premium-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="tp-section-label">Smart contract selection</p><h2 className="mt-1 text-lg font-black text-white">Best liquid contracts</h2></div>{decision&&<span className={`rounded-full px-3 py-1 text-[10px] font-black ${decision.decision==="QUALIFIED"?"bg-emerald-400/10 text-emerald-300":"bg-rose-400/10 text-rose-300"}`}>{decision.decision}</span>}</div>
 {decision?.contract&&<div className="mt-4 rounded-xl border border-violet-400/20 bg-violet-400/[.05] p-4"><div className="grid gap-3 sm:grid-cols-4"><div><p className="tp-section-label">Contract</p><b className="text-white">{decision.contract.strike} {decision.contract.option_type}</b></div><div><p className="tp-section-label">Entry</p><b className="text-white">₹{decision.entry}</b></div><div><p className="tp-section-label">SL / Target</p><b className="text-white">₹{decision.stop} / ₹{decision.target}</b></div><div><p className="tp-section-label">Size</p><b className="text-white">{decision.quantity} ({decision.lots} lot)</b></div></div><button disabled={opening||decision.decision!=="QUALIFIED"} onClick={()=>void paperBuy()} className="mt-4 w-full rounded-xl bg-emerald-500 px-4 py-3 text-sm font-black text-slate-950 disabled:opacity-40">{opening?"Opening virtual position…":"PAPER BUY · NO BROKER ORDER"}</button></div>}
 <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="py-3">Strike</th><th>Type</th><th>LTP</th><th>Spread</th><th>OI</th><th>Volume</th><th>IV</th><th>Delta</th><th>Score</th></tr></thead><tbody>{candidates.map(x=><tr key={`${x.strike}-${x.option_type}`} className="border-t border-white/5"><td className="py-3 font-black text-white">{x.strike}</td><td className="font-bold">{x.option_type}</td><td>₹{x.last_price.toFixed(2)}</td><td>{x.score_components.spread_percent.toFixed(2)}%</td><td>{x.oi.toLocaleString()}</td><td>{x.volume.toLocaleString()}</td><td>{x.iv.toFixed(1)}</td><td>{x.delta.toFixed(2)}</td><td className="font-black text-violet-300">{x.score}</td></tr>)}{!candidates.length&&<tr><td colSpan={9} className="py-16 text-center text-sm text-slate-600">Select an underlying and expiry, then scan the live Dhan option chain.</td></tr>}</tbody></table></div></article></section>

 <section className="mt-5 tp-premium-card rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="tp-section-label">Live paper positions</p><h2 className="mt-1 text-lg font-black text-white">Option positions · marked every 3 seconds</h2></div><span className="text-xs font-bold text-slate-500">Virtual only</span></div>{!positions.length?<p className="mt-6 rounded-xl bg-white/[.03] p-8 text-center text-sm text-slate-500">No open option paper positions.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="py-3">Contract</th><th>Expiry</th><th>Qty</th><th>Entry</th><th>LTP</th><th>SL</th><th>Target</th><th>P&L</th><th>Status</th></tr></thead><tbody>{positions.map(p=><tr key={p.id} className="border-t border-white/5"><td className="py-3 font-black text-white">{p.underlying} {p.strike} {p.option_type}</td><td>{p.expiry}</td><td>{p.quantity}</td><td>₹{p.entry_price.toFixed(2)}</td><td>{p.last_price==null?"—":`₹${p.last_price.toFixed(2)}`}</td><td>₹{p.stop_price.toFixed(2)}</td><td>₹{p.target_price.toFixed(2)}</td><td className={p.pnl>=0?"font-black text-emerald-300":"font-black text-rose-300"}>₹{p.pnl.toFixed(2)}</td><td>{p.status}</td></tr>)}</tbody></table></div>}</section>
 <section className="mt-5 grid gap-4 md:grid-cols-3"><div className="tp-kpi"><p className="tp-section-label">Entry</p><p className="mt-2 text-sm font-black text-white">BUY option premium only</p></div><div className="tp-kpi"><p className="tp-section-label">Risk</p><p className="mt-2 text-sm font-black text-white">25% premium stop · 50% target</p></div><div className="tp-kpi"><p className="tp-section-label">Execution</p><p className="mt-2 text-sm font-black text-amber-300">Broker orders permanently blocked here</p></div></section>
 </main>;
}
