import { useState } from "react";
import { api } from "../services/api";

type Evidence = {
  interval: string;
  requested_symbols: string[];
  missing_symbols: string[];
  cross_stock: { summary: { symbols_tested: number; robust_symbols: number; robust_percent: number; average_return_percent: number; median_profit_factor: number; worst_drawdown_percent: number }; ranking: Array<{ symbol: string; score: number; metrics: { return_percent: number; trades: number; profit_factor: number | null; max_drawdown_percent: number }; robustness: { status: string; reasons: string[] } }> };
  historical_out_of_sample: { summary: { symbols_tested: number; passed_symbols: number; pass_percent: number }; ranked: Array<{ symbol: string; status: string; out_of_sample: { trades: number; return_percent: number; profit_factor: number | null; max_drawdown_percent: number }; reasons: string[] }> };
};

const defaults = { trade_direction:"LONG_ONLY", initial_capital:100000, brokerage_rate:.0003, slippage_rate:.0005, max_daily_loss_percent:1, max_trades_per_session:3, opening_bars:3, fast_period:9, slow_period:20, volume_period:20, min_volume_ratio:1.5, max_gap_percent:3, risk_per_trade:.005, max_position_percent:.2, atr_period:14, atr_stop_multiple:1.5, reward_multiple:2, min_trades:30, min_profit_factor:1.1, min_positive_sensitivity_percent:60, min_stable_profit_factor_percent:60, max_drawdown_percent:15, min_walk_forward_success_percent:55 };

export default function IntradayEvidencePage() {
  const [symbols, setSymbols] = useState("TCS,INFY,RELIANCE,HDFCBANK,ICICIBANK,SBIN");
  const [interval, setInterval] = useState("5");
  const [result, setResult] = useState<Evidence | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function run() {
    setLoading(true); setError("");
    try { setResult(await api.post<Evidence>(`/strategy-builder/evidence?symbols=${encodeURIComponent(symbols)}&interval=${interval}&train_fraction=0.70`, defaults)); }
    catch (e) { setError(e instanceof Error ? e.message : "Evidence scan failed."); }
    finally { setLoading(false); }
  }
  return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Research</p><h1 className="text-3xl font-bold">Intraday Evidence</h1><p className="mt-2 text-slate-600">One controlled report for cross-stock and chronological out-of-sample evidence.</p></div><div className="flex gap-2"><select value={interval} onChange={e=>setInterval(e.target.value)} className="rounded-lg border bg-white px-3 py-2"><option>5</option><option>15</option><option>1</option><option>25</option><option>60</option></select><button onClick={()=>void run()} disabled={loading} className="rounded-lg bg-slate-950 px-5 py-2 font-semibold text-white transition hover:-translate-y-0.5 disabled:opacity-60">{loading?"Scanning…":"Run evidence scan"}</button></div></header>
    <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><label className="text-xs font-semibold uppercase tracking-wider text-slate-500">Research basket</label><input value={symbols} onChange={e=>setSymbols(e.target.value.toUpperCase())} className="mt-2 w-full rounded-xl border px-4 py-3 font-medium"/><p className="mt-2 text-xs text-slate-500">Same fixed parameters are used across every symbol. No per-stock optimization.</p></section>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
    {result&&<><section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Stocks",result.cross_stock.summary.symbols_tested],["Robust",`${result.cross_stock.summary.robust_percent}%`],["Avg return",`${result.cross_stock.summary.average_return_percent}%`],["Median PF",result.cross_stock.summary.median_profit_factor],["Worst DD",`${result.cross_stock.summary.worst_drawdown_percent}%`]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-1"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div>)}</section>
    <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Cross-stock scorecard</p><h2 className="text-xl font-bold">Consistency by symbol</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Fixed parameters</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-3">Symbol</th><th>Score</th><th>Return</th><th>Trades</th><th>PF</th><th>DD</th><th>Status</th></tr></thead><tbody>{result.cross_stock.ranking.map(item=><tr key={item.symbol} className="border-b last:border-0"><td className="py-3 font-bold">{item.symbol}</td><td>{item.score}</td><td>{item.metrics.return_percent}%</td><td>{item.metrics.trades}</td><td>{item.metrics.profit_factor??"—"}</td><td>{item.metrics.max_drawdown_percent}%</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.robustness.status==="ROBUST"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{item.robustness.status}</span></td></tr>)}</tbody></table></div></section>
    <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Out-of-sample validation</p><h2 className="text-xl font-bold">Chronological holdout</h2></div><div className="text-right"><p className="text-2xl font-extrabold">{result.historical_out_of_sample.summary.pass_percent}%</p><p className="text-xs text-slate-500">symbols passed</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{result.historical_out_of_sample.ranked.map(item=><div key={item.symbol} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between"><span className="font-bold">{item.symbol}</span><span className={`text-xs font-bold ${item.status==="PASS"?"text-emerald-700":"text-amber-700"}`}>{item.status}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p className="text-slate-500">Trades</p><b>{item.out_of_sample.trades}</b></div><div><p className="text-slate-500">Return</p><b>{item.out_of_sample.return_percent}%</b></div><div><p className="text-slate-500">PF</p><b>{item.out_of_sample.profit_factor??"—"}</b></div></div>{item.reasons.length>0&&<p className="mt-3 text-xs text-amber-700">{item.reasons.join(" · ")}</p>}</div>)}</div></section></>}
    <div className="mt-5 rounded-xl bg-slate-950 p-4 text-sm text-white"><strong>Research boundary:</strong> this report measures evidence; it does not optimize parameters and it does not authorize live trading.</div>
  </div></main>;
}
