import { useEffect, useState } from "react";
import { api } from "../services/api";

type Trade = { id:number; symbol:string; quantity:number; entry_price:number; stop_price:number; target_price:number; exit_price:number|null; pnl:number|null; status:"OPEN"|"CLOSED"; strategy_version:string; exit_reason:string|null; created_at:string; closed_at:string|null };
type Response = { trades:Trade[]; summary:{ trades:number; open_trades:number; closed_trades:number; realized_pnl:number; winning_trades:number; losing_trades:number; win_rate_percent:number; mode:string } };

type DhanResult = { mode:string; symbol:string; interval:string; processed_bars:number; buy_entries:number; dataset_valid:boolean };

export default function PaperTradingPage(){
 const [data,setData]=useState<Response|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[syncing,setSyncing]=useState(false),[syncResult,setSyncResult]=useState<DhanResult|null>(null);
 const [symbol,setSymbol]=useState("TCS"),[session,setSession]=useState(""),[interval,setIntervalValue]=useState("5");
 async function load(){setLoading(true);try{setData(await api.get<Response>("/paper-trading/trades"));setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load paper trading.");}finally{setLoading(false);}}
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(id)},[]);
 const close=async(t:Trade)=>{try{await api.post(`/paper-trading/trades/${t.id}/close`,{exit_price:t.entry_price,reason:"MANUAL"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to close trade.")}};
 const runDhan=async()=>{setSyncing(true);setError("");setSyncResult(null);try{setSyncResult(await api.post<DhanResult>("/paper-trading/session/dhan",{symbol,session,interval}));await load()}catch(e){setError(e instanceof Error?e.message:"Unable to run Dhan paper session.")}finally{setSyncing(false)}};
 return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Simulation</p><h1 className="text-3xl font-bold">Paper Trading</h1><p className="mt-2 text-slate-600">Long-only virtual execution. No broker orders are sent.</p></div><div className="rounded-full bg-emerald-50 px-4 py-2 text-xs font-bold text-emerald-700">SIMULATION ONLY</div></header>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-bold">Run market-data paper session</h2><p className="mt-1 text-xs text-slate-500">Uses connected Dhan historical candles. The result remains simulation-only.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">Dhan → Strategy → Virtual Order</span></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Trading date<input type="date" value={session} onChange={e=>setSession(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Interval<select value={interval} onChange={e=>setIntervalValue(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="1">1 min</option><option value="5">5 min</option><option value="15">15 min</option><option value="25">25 min</option><option value="60">60 min</option></select></label><button disabled={!symbol||!session||syncing} onClick={()=>void runDhan()} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50">{syncing?"Running…":"Run paper session"}</button></div>{syncResult&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><span className="font-bold">{syncResult.symbol}</span> · {syncResult.processed_bars} bars processed · {syncResult.buy_entries} BUY entries · dataset {syncResult.dataset_valid?"valid":"needs review"}</div>}</section>
 {loading&&!data?<div className="mt-6 grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-24 animate-pulse rounded-2xl bg-white shadow-sm"/>)}</div>:data&&<><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Realized P&L",`₹${data.summary.realized_pnl.toFixed(2)}`],["Win rate",`${data.summary.win_rate_percent}%`],["Open trades",String(data.summary.open_trades)],["Total trades",String(data.summary.trades)]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</section><section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Virtual positions</h2><p className="text-xs text-slate-500">Refreshed every 15 seconds</p></div><button onClick={()=>void load()} className="rounded-lg border px-3 py-2 text-sm font-semibold transition hover:-translate-y-0.5">Refresh</button></div><div className="mt-4 overflow-x-auto">{data.trades.length===0?<div className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500">No paper trades yet. A qualified long signal can create the first virtual position.</div>:<table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-3">Symbol</th><th>Side</th><th>Entry</th><th>SL</th><th>Target</th><th>Status</th><th>P&L</th><th/></tr></thead><tbody>{data.trades.map(t=><tr key={t.id} className="border-b last:border-0"><td className="py-3 font-bold">{t.symbol}</td><td><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">BUY</span></td><td>₹{t.entry_price}</td><td>₹{t.stop_price}</td><td>₹{t.target_price}</td><td>{t.status}</td><td className="font-semibold">{t.pnl==null?"—":`₹${t.pnl.toFixed(2)}`}</td><td>{t.status==="OPEN"&&<button onClick={()=>void close(t)} className="rounded-lg border px-2 py-1 text-xs font-semibold">Close</button>}</td></tr>)}</tbody></table>}</div></section></>}
 <p className="mt-5 text-xs text-slate-500">Paper results are simulations and do not establish future profitability. Validate slippage, costs, drawdown and out-of-sample performance before any live deployment.</p></div></main>
}
