import { useEffect, useState } from "react";
import { api } from "../services/api";

type Trade = { id:number; symbol:string; quantity:number; entry_price:number; stop_price:number; target_price:number; exit_price:number|null; pnl:number|null; status:"OPEN"|"CLOSED"; strategy_version:string; reason:string|null; created_at:string; closed_at:string|null };
type Dashboard = { mode:string; summary:{ trades:number; open_trades:number; closed_trades:number; realized_pnl:number; win_rate_percent:number }; performance:{ summary:{ realized_pnl:number; win_rate_percent:number; closed_trades:number; open_trades:number }; by_symbol:Record<string,{trades:number;closed_trades:number;pnl:number;win_rate_percent:number}>; exit_reasons:Record<string,number> }; open_positions:Array<{id:number;symbol:string;quantity:number;entry_price:number;stop_price:number;target_price:number;pnl:number;strategy_version:string}>; risk:{trade_direction:string;broker_orders_enabled:boolean;max_daily_loss_enforced:boolean;strategy_version_filter:string} };
type DhanResult = { mode:string; symbol:string; interval:string; processed_bars:number; buy_entries:number; persisted_trades:number; dataset_valid:boolean };

function money(v:number){return `₹${v.toFixed(2)}`;}

export default function PaperTradingPage(){
 const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[syncing,setSyncing]=useState(false),[syncResult,setSyncResult]=useState<DhanResult|null>(null),[filter,setFilter]=useState<"ALL"|"V1"|"V2">("ALL"),[closing,setClosing]=useState<number|null>(null),[exitPrices,setExitPrices]=useState<Record<number,string>>({});
 const [symbol,setSymbol]=useState("TCS"),[session,setSession]=useState(""),[interval,setIntervalValue]=useState("5");
 async function load(silent=false){if(!silent)setLoading(true);try{const q=filter==="ALL"?"":"?strategy_version="+filter;setData(await api.get<Dashboard>(`/paper-trading/dashboard${q}`));setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load paper trading.");}finally{setLoading(false);}}
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(true),10000);return()=>window.clearInterval(id)},[filter]);
 const close=async(t:Trade)=>{const raw=exitPrices[t.id]?.trim();const exit=Number(raw);if(!raw||!Number.isFinite(exit)||exit<=0){setError(`Enter a valid exit price for ${t.symbol} before closing.`);return;}setClosing(t.id);try{await api.post(`/paper-trading/trades/${t.id}/close`,{exit_price:exit,reason:"MANUAL"});setExitPrices(p=>({...p,[t.id]:""}));await load(true)}catch(e){setError(e instanceof Error?e.message:"Unable to close trade.")}finally{setClosing(null)}};
 const runDhan=async()=>{setSyncing(true);setError("");setSyncResult(null);try{setSyncResult(await api.post<DhanResult>("/paper-trading/session/dhan",{symbol,session,interval}));await load(true)}catch(e){setError(e instanceof Error?e.message:"Unable to run Dhan paper session.")}finally{setSyncing(false)}};
 const summary=data?.summary;
 return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Simulation control center</p><h1 className="text-3xl font-bold">Paper Trading</h1><p className="mt-2 text-slate-600">Long-first virtual execution with explicit risk boundaries. No broker orders are sent.</p></div><div className="flex items-center gap-2"><span className="animate-pulse rounded-full bg-emerald-100 px-4 py-2 text-xs font-bold text-emerald-700">● SIMULATION ONLY</span><select value={filter} onChange={e=>setFilter(e.target.value as "ALL"|"V1"|"V2")} className="rounded-full border bg-white px-3 py-2 text-xs font-bold"><option value="ALL">All strategies</option><option value="V1">V1 only</option><option value="V2">V2 only</option></select></div></header>
  {error&&<div className="mt-5 animate-in rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
  <section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="bg-slate-950 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-400">Historical replay</p><h2 className="mt-1 text-xl font-bold">Dhan → Strategy → Virtual Order</h2><p className="mt-1 text-sm text-slate-300">Replay a market session without sending any real order.</p></div><span className="rounded-full border border-slate-700 px-3 py-1 text-xs font-semibold">Long-first</span></div></div><div className="grid gap-3 p-5 sm:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Trading date<input type="date" value={session} onChange={e=>setSession(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Interval<select value={interval} onChange={e=>setIntervalValue(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="1">1 min</option><option value="5">5 min</option><option value="15">15 min</option><option value="25">25 min</option><option value="60">60 min</option></select></label><button disabled={!symbol||!session||syncing} onClick={()=>void runDhan()} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white ring-1 ring-slate-700 transition hover:-translate-y-0.5 hover:ring-slate-400 disabled:cursor-not-allowed disabled:opacity-50">{syncing?"Replaying…":"Run paper session"}</button></div>{syncResult&&<div className="mx-5 mb-5 grid gap-2 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-4"><span><b>{syncResult.symbol}</b> · {syncResult.processed_bars} bars</span><span>{syncResult.buy_entries} BUY entries</span><span><b>{syncResult.persisted_trades}</b> trades persisted</span><span>dataset {syncResult.dataset_valid?"valid":"needs review"}</span></div>}</section>
  {loading&&!data?<div className="mt-6 grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-white shadow-sm"/>)}</div>:data&&<>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Realized P&L",money(summary?.realized_pnl??0)],["Win rate",`${summary?.win_rate_percent??0}%`],["Open positions",String(summary?.open_trades??0)],["Closed trades",String(summary?.closed_trades??0)]].map(([label,value],i)=><div key={label} className="rounded-2xl border bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-md" style={{animationDelay:`${i*70}ms`}}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</section>
   <section className="mt-4 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-5 shadow-sm lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold">Risk guardrails</h2><p className="text-xs text-slate-500">The paper environment deliberately blocks real execution.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Protected</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Direction</p><p className="mt-1 font-bold">{data.risk.trade_direction}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Daily loss gate</p><p className="mt-1 font-bold">{data.risk.max_daily_loss_enforced?"ENFORCED":"OFF"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Broker orders</p><p className="mt-1 font-bold">{data.risk.broker_orders_enabled?"ENABLED":"BLOCKED"}</p></div></div></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Evidence progress</h2><p className="mt-2 text-sm text-slate-500">Closed trades contribute to the strategy-readiness sample. Research qualification remains separate.</p><div className="mt-4"><div className="flex justify-between text-xs font-semibold"><span>Paper sample</span><span>{summary?.closed_trades??0} / 30</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500 transition-all duration-700" style={{width:`${Math.min(100,((summary?.closed_trades??0)/30)*100)}%`}}/></div></div></div></section>
   <section className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Virtual positions</h2><p className="text-xs text-slate-500">Auto-refreshes every 10 seconds · filter: {data.risk.strategy_version_filter}</p></div><button onClick={()=>void load()} className="rounded-lg border px-3 py-2 text-sm font-semibold transition hover:-translate-y-0.5">Refresh</button></div><div className="mt-4 overflow-x-auto">{data.open_positions.length===0?<div className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500">No open paper positions.</div>:<table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-3">Symbol</th><th>Strategy</th><th>Entry</th><th>SL</th><th>Target</th><th>Qty</th><th>P&L</th><th>Manual exit</th></tr></thead><tbody>{data.open_positions.map(t=><tr key={t.id} className="border-b transition hover:bg-slate-50 last:border-0"><td className="py-3 font-bold">{t.symbol}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{t.strategy_version}</span></td><td>{money(t.entry_price)}</td><td>{money(t.stop_price)}</td><td>{money(t.target_price)}</td><td>{t.quantity}</td><td className={t.pnl>=0?"font-semibold text-emerald-700":"font-semibold text-red-700"}>{money(t.pnl)}</td><td><div className="flex gap-2"><input value={exitPrices[t.id]??""} onChange={e=>setExitPrices(p=>({...p,[t.id]:e.target.value}))} placeholder="price" className="w-24 rounded-lg border px-2 py-1.5 text-xs"/><button disabled={closing===t.id} onClick={()=>void close(t as unknown as Trade)} className="rounded-lg border px-2 py-1.5 text-xs font-semibold transition hover:-translate-y-0.5 disabled:opacity-50">{closing===t.id?"…":"Close"}</button></div></td></tr>)}</tbody></table>}</div></section>
   <section className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Performance by stock</h2><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{Object.entries(data.performance.by_symbol).map(([stock,v])=><div key={stock} className="rounded-xl border p-4 transition hover:-translate-y-0.5"><div className="flex justify-between"><span className="font-bold">{stock}</span><span className={v.pnl>=0?"text-emerald-700":"text-red-700"}>{money(v.pnl)}</span></div><p className="mt-2 text-xs text-slate-500">{v.closed_trades} closed · {v.win_rate_percent}% win rate</p></div>)}{Object.keys(data.performance.by_symbol).length===0&&<p className="text-sm text-slate-500">No completed paper performance yet.</p>}</div></section>
  </>}
  <p className="mt-5 text-xs text-slate-500">Paper results are simulations and do not establish future profitability. TradePilot keeps live broker execution disabled while research, out-of-sample validation and paper evidence are being accumulated.</p>
 </div></main>
}
