import { useState } from "react";
import { api } from "../services/api";

type Config = { initial_capital:number; brokerage_rate:number; slippage_rate:number; max_daily_loss_percent:number; max_trades_per_session:number; opening_bars:number; fast_period:number; slow_period:number; volume_period:number; min_volume_ratio:number; max_gap_percent:number; risk_per_trade:number; max_position_percent:number; atr_period:number; atr_stop_multiple:number; reward_multiple:number };
type Metrics = { return_percent:number; trades:number; wins:number; losses:number; win_rate_percent:number; profit_factor:number|null; expectancy:number; max_drawdown_percent:number; ending_capital:number };
type Comparison = { symbol:string; interval:string; assumptions:{parameter_selection:boolean}; v1:Metrics & {strategy_version:string}; v2:Metrics & {strategy_version:string}; delta:{return_percent:number;profit_factor:number|null;win_rate_percent:number;max_drawdown_percent:number;expectancy:number} };
type WalkForward = { symbol:string; interval:string; parameter_selection:boolean; windows:number; train_size:number; validation_size:number; v1:{summary:{windows:number;profitable_windows:number;success_rate_percent:number;average_return_percent:number;worst_return_percent:number;max_drawdown_percent:number}}; v2:{summary:{windows:number;profitable_windows:number;success_rate_percent:number;average_return_percent:number;worst_return_percent:number;max_drawdown_percent:number}} };
const defaults:Config={initial_capital:100000,brokerage_rate:.0003,slippage_rate:.0005,max_daily_loss_percent:1,max_trades_per_session:3,opening_bars:3,fast_period:9,slow_period:20,volume_period:20,min_volume_ratio:1.5,max_gap_percent:3,risk_per_trade:.005,max_position_percent:.2,atr_period:14,atr_stop_multiple:1.5,reward_multiple:2};
export default function StrategyBuilderPage(){
 const [symbol,setSymbol]=useState("TCS"),[interval,setInterval]=useState("5"),[cfg,setCfg]=useState(defaults),[result,setResult]=useState<Metrics|null>(null),[comparison,setComparison]=useState<Comparison|null>(null),[walk,setWalk]=useState<WalkForward|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const set=(key:keyof Config,value:string)=>setCfg(c=>({...c,[key]:Number(value)}));
 const query=()=>`?symbol=${encodeURIComponent(symbol)}&interval=${interval}`;
 async function run(kind:"backtest"|"compare"|"walk-forward"){setLoading(true);setError("");try{if(kind==="backtest"){setResult(await api.post<Metrics & {symbol:string}>(`/strategy-builder/backtest${query()}`,cfg));setComparison(null);setWalk(null);}else if(kind==="compare"){setComparison(await api.post<Comparison>(`/strategy-builder/compare${query()}`,cfg));setResult(null);setWalk(null);}else{setWalk(await api.post<WalkForward>(`/strategy-builder/walk-forward${query()}&train_size=60&validation_size=20`,cfg));setResult(null);setComparison(null);}}catch(e){setError(e instanceof Error?e.message:"Research run failed.");}finally{setLoading(false);}}
 const field=(key:keyof Config,label:string,step="0.1")=><label><span className="text-xs font-semibold text-slate-500">{label}</span><input type="number" step={step} value={cfg[key]} onChange={e=>set(key,e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:ring-2 focus:ring-slate-300"/></label>;
 const metric=(label:string,value:string)=><div className="rounded-xl bg-slate-50 p-4 transition hover:-translate-y-0.5"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>;
 return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Research</p><h1 className="text-3xl font-bold">Strategy Builder</h1><p className="mt-2 text-slate-600">Build, compare and validate the intraday engine before paper trading.</p></div><div className="flex flex-wrap gap-2"><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} className="w-32 rounded-lg border bg-white px-3 py-2 font-semibold"/><select value={interval} onChange={e=>setInterval(e.target.value)} className="rounded-lg border bg-white px-3 py-2"><option>5</option><option>15</option><option>1</option><option>25</option><option>60</option></select><button onClick={()=>void run("backtest")} disabled={loading} className="rounded-lg bg-slate-950 px-4 py-2 font-semibold text-white transition hover:-translate-y-0.5 disabled:opacity-60">{loading?"Running…":"Backtest"}</button><button onClick={()=>void run("compare")} disabled={loading} className="rounded-lg border bg-white px-4 py-2 font-semibold transition hover:-translate-y-0.5 disabled:opacity-60">Compare V1/V2</button><button onClick={()=>void run("walk-forward")} disabled={loading} className="rounded-lg border bg-white px-4 py-2 font-semibold transition hover:-translate-y-0.5 disabled:opacity-60">Walk-forward</button></div></header>
 <div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Entry & trend rules</h2><p className="text-xs text-slate-500">Parameters are fixed for validation; results do not tune them.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">No live orders</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{field("opening_bars","Opening bars","1")}{field("fast_period","Fast EMA","1")}{field("slow_period","Slow EMA","1")}{field("volume_period","Volume period","1")}{field("min_volume_ratio","Min volume ratio","0.1")}{field("max_gap_percent","Max opening gap %","0.1")}{field("atr_period","ATR period","1")}{field("atr_stop_multiple","ATR stop multiple","0.1")}{field("reward_multiple","Reward multiple","0.1")}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Risk & execution</h2><div className="mt-4 grid gap-4">{field("initial_capital","Initial capital","1000")}{field("risk_per_trade","Risk per trade","0.001")}{field("max_position_percent","Max position %","0.01")}{field("max_daily_loss_percent","Max daily loss %","0.1")}{field("max_trades_per_session","Max trades / session","1")}{field("brokerage_rate","Brokerage rate","0.0001")}{field("slippage_rate","Slippage rate","0.0001")}</div></section></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
 {result&&<section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-500">Backtest result</p><h2 className="text-2xl font-bold">{symbol} · {interval} min</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Research only</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metric("Return",`${result.return_percent}%`)}{metric("Profit factor",result.profit_factor?.toFixed(2)??"—")}{metric("Win rate",`${result.win_rate_percent}%`)}{metric("Expectancy",result.expectancy.toFixed(2))}{metric("Max drawdown",`${result.max_drawdown_percent}%`)}</div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Trades</p><p className="font-semibold">{result.trades} ({result.wins}W / {result.losses}L)</p></div><div><p className="text-xs text-slate-500">Ending capital</p><p className="font-semibold">₹{result.ending_capital.toLocaleString()}</p></div></div></section>}
 {comparison&&<section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-500">Controlled comparison</p><h2 className="text-2xl font-bold">V1 vs V2</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">Parameter selection: OFF</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-3">Metric</th><th>V1</th><th>V2</th><th>Delta</th></tr></thead><tbody>{([["Return",comparison.v1.return_percent,comparison.v2.return_percent,comparison.delta.return_percent],["Win rate",comparison.v1.win_rate_percent,comparison.v2.win_rate_percent,comparison.delta.win_rate_percent],["Profit factor",comparison.v1.profit_factor,comparison.v2.profit_factor,comparison.delta.profit_factor],["Expectancy",comparison.v1.expectancy,comparison.v2.expectancy,comparison.delta.expectancy],["Max drawdown",comparison.v1.max_drawdown_percent,comparison.v2.max_drawdown_percent,comparison.delta.max_drawdown_percent]] as Array<[string,number|null,number|null,number|null]>).map(([l,a,b,d])=><tr key={l} className="border-b last:border-0"><td className="py-3 font-semibold">{l}</td><td>{a??"—"}</td><td>{b??"—"}</td><td className="font-semibold">{d??"—"}</td></tr>)}</tbody></table></div></section>}
 {walk&&<section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs uppercase tracking-wider text-slate-500">Out-of-sample validation</p><h2 className="text-2xl font-bold">Walk-forward · {walk.windows} windows</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Fixed parameters</span></div><div className="mt-5 grid gap-5 md:grid-cols-2">{([["V1",walk.v1.summary],["V2",walk.v2.summary]] as const).map(([name,s])=><div key={name} className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold">{name}</h3><div className="mt-4 grid grid-cols-2 gap-3">{metric("Success rate",`${s.success_rate_percent}%`)}{metric("Avg return",`${s.average_return_percent}%`)}{metric("Worst return",`${s.worst_return_percent}%`)}{metric("Max DD",`${s.max_drawdown_percent}%`)}</div></div>)}</div><p className="mt-4 text-xs text-slate-500">Training windows are chronological context only. No parameter optimization is performed inside these windows.</p></section>}
 <p className="mt-5 text-xs text-slate-500">Historical simulations are not guarantees. A strategy must survive out-of-sample testing and paper trading before any live deployment decision.</p></div></main>;
}
