import { useState } from "react";
import { apiRequest } from "../services/api";

type Config = { initial_capital:number; brokerage_rate:number; slippage_rate:number; max_daily_loss_percent:number; max_trades_per_session:number; opening_bars:number; fast_period:number; slow_period:number; volume_period:number; min_volume_ratio:number; max_gap_percent:number; risk_per_trade:number; max_position_percent:number; atr_period:number; atr_stop_multiple:number; reward_multiple:number };
type Result = { symbol:string; interval:string; execution:Record<string,number>; return_percent:number; trades:number; wins:number; losses:number; win_rate_percent:number; profit_factor:number|null; expectancy:number; max_drawdown_percent:number; ending_capital:number };
const defaults:Config={initial_capital:100000,brokerage_rate:.0003,slippage_rate:.0005,max_daily_loss_percent:1,max_trades_per_session:3,opening_bars:3,fast_period:9,slow_period:20,volume_period:20,min_volume_ratio:1.5,max_gap_percent:3,risk_per_trade:.005,max_position_percent:.2,atr_period:14,atr_stop_multiple:1.5,reward_multiple:2};
export default function StrategyBuilderPage(){
 const [symbol,setSymbol]=useState("TCS"),[interval,setInterval]=useState("5"),[cfg,setCfg]=useState(defaults),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const set=(key:keyof Config,value:string)=>setCfg(c=>({...c,[key]:Number(value)}));
 async function run(){setLoading(true);setError("");setResult(null);try{setResult(await apiRequest<Result>(`/strategy-builder/backtest?symbol=${encodeURIComponent(symbol)}&interval=${interval}`,{method:"POST",body:JSON.stringify(cfg)}));}catch(e){setError(e instanceof Error?e.message:"Backtest failed.");}finally{setLoading(false);}}
 const field=(key:keyof Config,label:string,step="0.1")=><label><span className="text-xs font-semibold text-slate-500">{label}</span><input type="number" step={step} value={cfg[key]} onChange={e=>set(key,e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-slate-300"/></label>;
 return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Research</p><h1 className="text-3xl font-bold">Strategy Builder</h1><p className="mt-2 text-slate-600">Configure the intraday engine and backtest it against stored NSE data.</p></div><div className="flex gap-2"><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} className="w-32 rounded-lg border bg-white px-3 py-2 font-semibold"/><select value={interval} onChange={e=>setInterval(e.target.value)} className="rounded-lg border bg-white px-3 py-2"><option>5</option><option>15</option><option>1</option><option>25</option><option>60</option></select><button onClick={()=>void run()} disabled={loading} className="rounded-lg bg-slate-950 px-5 py-2 font-semibold text-white transition hover:-translate-y-0.5 disabled:opacity-60">{loading?"Running…":"Run backtest"}</button></div></header>
 <div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Entry & trend rules</h2><p className="text-xs text-slate-500">These parameters directly configure the intraday engine.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">No live orders</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{field("opening_bars","Opening bars","1")}{field("fast_period","Fast EMA","1")}{field("slow_period","Slow EMA","1")}{field("volume_period","Volume period","1")}{field("min_volume_ratio","Min volume ratio","0.1")}{field("max_gap_percent","Max opening gap %","0.1")}{field("atr_period","ATR period","1")}{field("atr_stop_multiple","ATR stop multiple","0.1")}{field("reward_multiple","Reward multiple","0.1")}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Risk & execution</h2><div className="mt-4 grid gap-4">{field("initial_capital","Initial capital","1000")}{field("risk_per_trade","Risk per trade","0.001")}{field("max_position_percent","Max position %","0.01")}{field("max_daily_loss_percent","Max daily loss %","0.1")}{field("max_trades_per_session","Max trades / session","1")}{field("brokerage_rate","Brokerage rate","0.0001")}{field("slippage_rate","Slippage rate","0.0001")}</div></section></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
 {result&&<section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-slate-500">Backtest result</p><h2 className="text-2xl font-bold">{result.symbol} · {result.interval} min</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Research only</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Return",`${result.return_percent}%`],["Profit factor",result.profit_factor?.toFixed(2)??"—"],["Win rate",`${result.win_rate_percent}%`],["Expectancy",result.expectancy.toFixed(2)],["Max drawdown",`${result.max_drawdown_percent}%`]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 text-xl font-bold">{v}</p></div>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Trades</p><p className="font-semibold">{result.trades} ({result.wins}W / {result.losses}L)</p></div><div><p className="text-xs text-slate-500">Ending capital</p><p className="font-semibold">₹{result.ending_capital.toLocaleString()}</p></div><div><p className="text-xs text-slate-500">Execution</p><p className="font-semibold">{(result.execution.slippage_rate*100).toFixed(2)}% slippage · {(result.execution.brokerage_rate*100).toFixed(2)}% brokerage</p></div></div></section>}
 <p className="mt-5 text-xs text-slate-500">Historical simulations are not guarantees. Use walk-forward validation and paper trading before considering live deployment.</p></div></main>;
}
