import os


JWT_ALGORITHM = "HS256"

JWT_SECRET_KEY = os.getenv(
    "TRADEPILOT_JWT_SECRET",
    "development-only-secret-change-before-production",
)

JWT_EXPIRE_MINUTES = int(
    os.getenv(
        "TRADEPILOT_JWT_EXPIRE_MINUTES",
        "60",
    )
)

TRADEPILOT_AI_PROVIDER = os.getenv(
    "TRADEPILOT_AI_PROVIDER",
    "mock",
).strip().lower()

TRADEPILOT_AI_API_KEY = os.getenv("TRADEPILOT_AI_API_KEY", "")
TRADEPILOT_AI_MODEL = os.getenv("TRADEPILOT_AI_MODEL", "")
TRADEPILOT_AI_BASE_URL = os.getenv("TRADEPILOT_AI_BASE_URL", "")
TRADEPILOT_AI_TIMEOUT_SECONDS = float(os.getenv("TRADEPILOT_AI_TIMEOUT_SECONDS", "10"))
TRADEPILOT_AI_MAX_RETRIES = max(0, int(os.getenv("TRADEPILOT_AI_MAX_RETRIES", "1")))
TRADEPILOT_AI_RATE_LIMIT = max(1, int(os.getenv("TRADEPILOT_AI_RATE_LIMIT", "30")))
TRADEPILOT_AI_CACHE_TTL_SECONDS = max(1, int(os.getenv("TRADEPILOT_AI_CACHE_TTL_SECONDS", "300")))
TRADEPILOT_ALERT_COOLDOWN_SECONDS = max(1, int(os.getenv("TRADEPILOT_ALERT_COOLDOWN_SECONDS", "3600")))
